live_config_reload = true

[colors.cursor]
text = '#292929'
cursor = '#FF5269'

[colors.primary]
background= '#181818'
foreground= '#d6d6dd'

  # Bright colors
[colors.bright]
black = '#292929'
red = '#CC7C8A'
green = '#afcb85'
yellow = '#e5c995'
blue = '#52a7f6'
magenta = '#a390f0'
cyan = '#78d0bd'
white = '#d6d6dd'

  # Normal colors
[colors.normal]
black = '#292929'
red = '#CC7C8A'
green = '#afcb85'
yellow = '#e5c995'
blue = '#52a7f6'
magenta = '#a390f0'
cyan = '#78d0bd'
white = '#d6d6dd'

[colors.selection]
text= '#292929'
background= '#767676'

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Medium"

[mouse]
hide_when_typing = true 

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"
decorations = "None"

[window.padding]
x = 6
y = 1
